version: '3'

services:
  mediamtx:
    image: bluenviron/mediamtx:latest-ffmpeg
    network_mode: host
  ffmpeg-listener:
    build:
      context: ./ffmpeg-rtsp
    network_mode: host
  boda-ai-server:
    image: pytorch/pytorch:2.0.1-cuda11.7-cudnn8-runtime
    container_name: boda-ai-server
    hostname: boda-ai-server
    network_mode: host
    volumes:
      - ./boda-ai:/home/boda-ai
      - ./boda-ai-server.sh:/home/boda/boda-ai-server.sh
      - ./socket-server/SocketIOServer.java:/home/boda/SocketIOServer.java
      - /tmp/.X11-unix:/tmp/.X11-unix
    stdin_open: true
    tty: true
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
    environment:
      - DISPLAY=:0  # Set the display environment variable
    devices:
      - /dev/dri:/dev/dri
